Eco 1701 rcbpurchui pass the variables from the sdk to the paywall
RevenueCat/purchases-js pull request #240
Opened 2024-11-21 22:28 UTC by guido732

## Motivation / Description
Parses offering packages into an object keyed by package Identifier and a variables object as value.
Passes this object into the paywall initialization.

TODO: 
- Tests

## Changes introduced

## Linear ticket (if any)

## Additional comments

2024-11-22 12:11 UTC, nicfix reviewed
I think there are still some variables that we can calculate since we have trials.

I added a test with a full offering fixture so that it might be easier to iterate.

I also needed to change the import from `/src/main` since it was failing when running the tests locally.

2024-11-22 12:11 UTC, nicfix commented on src/helpers/variables-helpers.ts
> +    sub_offer_duration: undefined, // doesn't apply (yet)
I just added it and pushed it to this branch

2024-11-25 15:10 UTC, nicfix requested changes
A couple of suggestions on how we handle the divisions by zero and another test that might be useful.

Marking as request changes to make sure that we wait to ship this before having the next version of the SDK online. We need to update the package.json to make sure that nothing breaks

2024-11-25 15:10 UTC, nicfix commented on src/helpers/paywall-variables-helpers.ts
> +      (price.amountMicros * 4) / period.number,
Don't we need a check that `period.number > 1` also for this division?

2024-11-25 15:10 UTC, nicfix commented on src/helpers/paywall-variables-helpers.ts
> +      (price.amountMicros * 30) / period.number,
Don't we need a check that `period.number > 1` also for this division?

2024-11-25 15:10 UTC, nicfix commented on src/helpers/paywall-variables-helpers.ts
> +  if (period.unit === "month" && period.number > 1) {
Maybe you can early return here
```suggestion
  if(period.number == 0)
  {
     return fallback;
  }

  if (period.unit === "month" && period.number > 1) {
```

And avoid the following checks

2024-11-25 15:10 UTC, nicfix commented on src/helpers/paywall-variables-helpers.ts
> +  if (period.unit === "month") {
Also here `period.number` might be 0 causing a division by zero.

2024-11-25 15:10 UTC, nicfix commented on src/tests/helpers/paywall-variables-helper.test.ts
I would add a test to validate that the `sub_relative_discount` is calculated well w.r.t. the highest price.

The current test will definitely cover this specific use case but having also this rule covered might be a good idea if we change some logic in the future.

2024-11-26 15:50 UTC, nicfix reviewed
I'd just remove the copy of the VariablesDictionary class.

We can import it internally directly from `purchases-ui-js` and I don't think we need to export it publicly, if so we can just export the same type by doing

```
import type {VariablesDictionary as UIVariablesDictionary} from '@revenuecat/purchases-ui-js`

...

export const VariablesDictionary = UIVariablesDictionary
```

2024-11-26 15:55 UTC, guido732 commented on src/helpers/paywall-variables-helpers.ts
> +export type VariableDictionary = {
it wasn't to export it to users of the SDK but rather to be used elsewhere in the app, I'll just export it from `purchases-ui-js` and reuse it :) thanks for the suggestion

2024-11-26 15:55 UTC, guido732 commented on src/helpers/paywall-variables-helpers.ts
> +function getDurationInMonths(period: Period) {
🫠  localizations are hard

2024-11-26 16:46 UTC, nicfix approved these changes

2024-11-26 18:26 UTC, merged

2024-11-28 08:38 UTC, tonidero commented
@guido732 Changed labels to `pr:other`, since this is not a user facing change yet, so better to assign it to the the rest of the changelog.